### ISSUE TITLE
Mod breaks all Simple Start mods 

### ISSUE THREAD

**Issue by AlexBeez** [Gerkiz/RPG#1]
Title says it all. The mod breaks all mods that add inventory at the beginning of the game. 

It's a simple enough workaround - start new world, save, THEN enable mod, but thought you might still want to know. 

Loving it by the by.

**Comment by Gerkiz** [comment]
Happy that you enjoy the mod. This mod should not interfere with other mods inventory - since I add a rpg-string.

What mod are you using that breaks this?

**Comment by AlexBeez** [comment]
Other way around. 

Having this mod enabled prevents all other mods from adding inventory to the player AND stops the Crash cutscene from playing which prevents the ship from spawning which, as of 1.0.0, often has inventory too.

Examples of mods broken by this behavior: 

https://mods.factorio.com/mod/Kux-SpeedyBotStart
https://mods.factorio.com/mod/crash-quick-start
https://mods.factorio.com/mod/IngosAdvancedStart

**Comment by Gerkiz** [comment]
I'll load these mods and try to replicate this issue. I'll get back to you when I have a fix for this.

**Comment by Gerkiz** [comment]
I see the issue now.

What RPG does is - it applies the modifiers (below) to the player. So if there are any other mods that also does this then it will not work.

https://github.com/Gerkiz/RPG/blob/a0834fcb4ada66f2fdca01c200c2a3ed57b2c61b/utils/player_modifiers.lua#L24-L37

**Comment by AlexBeez** [comment]
That's interesting!
