### ISSUE TITLE
Mod broken when adding midgame

### ISSUE THREAD

**Issue by xBeathovenx** [Gerkiz/RPG#10]
Hi,

iam running KS2 + SE, i switched from RPG System to your mod after like 2hrs, but when i do i only get levels and cant distribute attributes.

**Comment by Gerkiz** [comment]
Hi,

Could you please provide a savegame so I can check it out?

**Comment by xBeathovenx** [comment]
sure, its an older one with only lvl3 was lvl22 when i tried it first.

https://mega.nz/file/rIgmASiT#OUFIDFaGdBxG9Ja6sC0ONeNmzJgvCgGH__au91hV6K8

**Comment by Gerkiz** [comment]
Thank you for the save game! I was able to find out what was causing the issue.
Apparently your players "points_left" attribute was missing? I have added a check for this so it should be fixed on version 1.0.12.

Could you confirm and get back? 👍 

/Gerkiz
