### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ErisAnn** [Gerkiz/RPG#13]
Causes crashes with Milestones and Territory Claim and isn't playing nice with GUI Unifyer anymore.
I was able to recreate their issues consistently with just RPG and only one of the above enabled at a time.

I reported these to the other mods, too.

https://i.imgur.com/Y5saRwA.png

When I open or close the RPG menu, Territory Claim crashes with this:

The mod Territory Claim (1.0.35) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event territory_claim::on_nth_tick(130)
__territory_claim__/control.lua:450: attempt to index field 'maf_main_menu_frame' (a nil value)
stack traceback:
	__territory_claim__/control.lua:450: in function 'check_player_land'
	__territory_claim__/control.lua:460: in function <__territory_claim__/control.lua:457>

Milestones crashes coming in or out of the main esc menu with this:

The mod Milestones (1.3.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Milestones::milestones_cancel_settings (ID 180)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__Milestones__/scripts/gui_settings_page.lua:415: in function 'is_settings_page_visible'
	__Milestones__/scripts/gui.lua:254: in function <__Milestones__/scripts/gui.lua:253>

**Comment by Gerkiz** [comment]
Hi there!

I think I have a fix for this.

**Comment by Gerkiz** [comment]
Posted at https://mods.factorio.com/mod/territory_claim/discussion/62fe965a2e425cec477311ac

Milestones seems to have fixed this.

Closing!
