### ISSUE TITLE
Pls add more info about mod

### ISSUE THREAD

**Issue by safronov-nikolai** [Gerkiz/RPG#14]
- How does magic work? What is mana used for?
- What is the XP number floating over the character, as it is not the same XP number that goes into the character sheet.
- What other mods are recommended to work with this one?

**Comment by Gerkiz** [comment]
Hi! Sorry for my delayed answer.

- Magic is simply "vanilla". Meaning you spawn entities that are from vanilla Factorio.
- Mana is used to "cast" spells - which in terms uses magic to calculate how much mana a player for example has.

- The floating XP number is a rounded number from a given tasks the player has done. It can either be a static number or rounded number from multiple sources.

- Currently, this mod should work with every other mod that does not interfere with the players character bonuses.
