### ISSUE TITLE
Mod interferes other MOD GUI's

### ISSUE THREAD

**Issue by TheoMarque** [Gerkiz/RPG#15]
After opening a window GUI from RPG mod, the [MaxRate ](https://mods.factorio.com/mod/RateCalculator) not working properly until game reset. Please, check the window generate process, because, without your mod, RateCalculator works fine.

**Comment by SniperKittensdad** [comment]
I Agree, this is an issue, unknown if other mods are also causing it as well, but this exact one also has an issue with Rate Calculator.

**Comment by Gerkiz** [comment]
I'll check it out! Ty for posting this!

**Comment by Gerkiz** [comment]
Almost 1 year later - it's fixed in 1.0.16.
