### ISSUE TITLE
What are the XP rates for different actions?

### ISSUE THREAD

**Issue by cjthedj402** [Gerkiz/RPG#16]
I am having trouble finding the xp rates for various actions (e.g. mining a tree vs. a rock, killing a small vs big biter, etc.) - how can I figure this out?

Thanks

**Comment by Gerkiz** [comment]
The rates are defined here:
For mining:
[https://github.com/Gerkiz/RPG/blob/447d6ad766c9443b57e95c496bfaede65f408831/rpg/main.lua#L620](url)

Biters:
[https://github.com/Gerkiz/RPG/blob/447d6ad766c9443b57e95c496bfaede65f408831/rpg/main.lua#L267](url)
