### ISSUE TITLE
How to cast spells (Resolved)

### ISSUE THREAD

**Issue by adelvalle** [Gerkiz/RPG#17]
For those that may stumble on this, and wonder how to cast spells. (Since I must be overlooking some instruction on this matter)

Step 1: Acquire Fish (looks to be a spell that will spawn those in later on)

Step 2: Have enough mana to be able to cast the spell, the wall spell being entry level requires 60 mana so you will need to put some points into mana.

Step 3: Open the RPG menu > Gear in the top right > click the fish icon

Step 4: you will now see a wonderful HUD with 3 spells. If you left it at default you will see three walls. That can be changed next to the fish icon in step 3. This is your spell hotbar. If the box under the fish is green you can cast. The numbers going from left to right represent "mana cost", "current mana", and "max mana" respectively. The mana cost is for the selected spell. 

Step 5: open inventory and have the fish in hand, or put fish on your hot bar. With the spell selected from the hotbar in step 4. (you should see a little 1 next to the spell, in my case "wall")

Step 6: For this example, I had wall. It has the "1" next to it to show that is selected. I see my pointer with the fish icon (with the # in my inventory) and I click Left mouse button "LMB"   and a wall spawns.

Congrats, magic!

**Comment by Gerkiz** [comment]
I'll pin this, just for the sake of it.

If you have a better explanation, then feel free to PR. 👍
