### ISSUE TITLE
Incompatibility With RecipeBook

### ISSUE THREAD

**Issue by Supertacoz** [Gerkiz/RPG#19]
When Using This mod and the Recipe Book mod at the same time, the recipe book menu cannot be brought up.

Log of session where I attempted to open recipe book: 
[factorio-current.log](https://github.com/Gerkiz/RPG/files/12755606/factorio-current.log)

**Comment by Supertacoz** [comment]
Actually, this might be incorrect. 
turns out this was a different mod. Ignore this.

**Comment by Supertacoz** [comment]
Nevermind, it does seem to be this mod.

**Comment by Supertacoz** [comment]
To reproduce the issue: 
1. Load a world with Recipe book and this mod enabled.
2. open the RPG menu at least once
3. attempt to open the recipe book.

**Comment by Gerkiz** [comment]
This is now fixed in 1.0.16.
Do note that opening RPG settings (cogwheel)
![image](https://github.com/Gerkiz/RPG/assets/39602942/9497bfa1-0b7f-447d-95c5-0524e9712fec)

Still closes the RecipeBook frame, since RPG utilizes `player.opened` and so does RecipeBook.

Thank you! 👍
