### ISSUE TITLE
Possible mod break/interaction issue: no stats increase anything except for Strength increasing melee damage

### ISSUE THREAD

**Issue by AlexBeez** [Gerkiz/RPG#2]

**Comment by Gerkiz** [comment]
Hello,

I need more information on what you mean - could you please clarify?

Thank you!

**Comment by AlexBeez** [comment]
While the mod is enabled, the only stat that increases is melee damage. All other stats - run speed, craft speed, player reach, inventory space - stay at their starting value.  

Now granted it could have been another mod doing that, but I couldn't pinpoint exactly what caused it. 

Note that Comfy RPG did not have this issue, either.

**Comment by Gerkiz** [comment]
I see. Thank you for this.

Could you please provide the mods that you are using? I would love to fix this.

**Comment by Gerkiz** [comment]
This seems to be identical to #3 - which is now fixed.
