### ISSUE TITLE
Allow Disabling Pickup Reach Bonus

### ISSUE THREAD

**Issue by Supertacoz** [Gerkiz/RPG#20]
I really like have extra reach when placing down buildings, but when picking up items off the ground, I would rather not have that because then I accidentally pick up a bunch of stuff I didn't want to.

Could it please be made so that the different types of reach bonuses can be turned off and on independently from one another?

**Comment by Gerkiz** [comment]
I've added this in 1.0.16. Feel free to test it out.

**Comment by Supertacoz** [comment]
Thank you!
