### ISSUE TITLE
What are some of these spells?

### ISSUE THREAD

**Issue by Wanaskiwin** [Gerkiz/RPG#22]
I've figured out that some of the spells just don't work and thats why i was confused. that said, what are some of these spells? Like whats charge? Does it recharge my energy? Does it refuel a vehicle? The spell book just says when its unlocked and not what it does.

Also How is spawning shotgun shells supposed to work do i need to have a chest near me? Does it need to be one i conjured? Im very confused.

**Comment by Wanaskiwin** [comment]
Also i think the point system needs a heavy rework, I get spells way before i can even realistically use them it seems. like i got fast belts but unless i was dedicated all 5 of my points per level to mana exclusively i wouldn't be able to use them, and it only casts one belt anyway, which is infinitely worse (even though its mostly free) than just crafting them, and maybe its because i have an enemy mod that changes how enemies work, but killing seems drastically worse than just crafting and moving around aimlessly, by a wide margin.

**Comment by Gerkiz** [comment]
Woops! Wrong button - however. All spells are confirmed to work and are just as intended. 

Charge is a similar spell from the known game Tibia.

**Comment by Gerkiz** [comment]
> Also i think the point system needs a heavy rework
Thank you for your input - however this will not change.

**Comment by Wanaskiwin** [comment]
Originally it was an issue i had posted, i'm not used to github and had missed the issue i had was pinned, apologies if editing it to something less of an issue is the incorrect chain of command but since I'm here, i raise the following issues. 


I had to google Tibia and hope the spell charge was named the same to find out its a move speed thing, a description of its own would be greatly helpful though, Like i presumed shotgun shells worked like belt or wall, where it'd give me a couple shotgun shells, it wasnt until i tried out HE and AP shell that i realized its a spell that casts shotgun blast on the cursor.

but I still think everything needs a major rework except maybe dex and biter summoning. 


I understand having a system where you get multiple points but the system currently only has any effect if you put all 5 points per level into a stat, so why not just make it one point per level? Aside the other benefits (of which made no impact on my gameplay) str gives an inventory slot every 5 points, so obviously im going to always put 5 into it when i level str, mana you need hundreds of and get 10 every 5 points, so im always going to put the full amount into it, vitality.... well 10 health isnt much, but its still better than putting one point and getting 2HP. putting the full level into dex also helps level you faster as well, hand crafting gets you the most XP it seems, so getting the most amount of crafting speed you can per level is a given (heck, its probably OP)

I get that casting a bunch of belts for the cost of a fish and some mana is kind of OP but in a game where you are already making thousands of belts, pipes, walls, etc is kind of like trying to move water with an eye dropper when the water fall next to you is doing the job anyway.

I think it might also be more useful to have assemblers, power poles and maybe miners or smelters instead of belts, pipes and boxes, burner inserters could also be good, and having some mana at the start would be very helpful for actually utilizing some of these factory related spells we get by being level one.
