### ISSUE TITLE
No Points to Distribute

### ISSUE THREAD

**Issue by DeNarr** [Gerkiz/RPG#3]
I'm up to level 14 and I still don't have a single point to distribute.

**Comment by ElizTriad** [comment]
Likewise. 152 level, no point to distribute.
https://cdn.discordapp.com/attachments/447413398695706645/758153514005954570/Screen-512.png

**Comment by Gerkiz** [comment]
I'll push a fix for this momentarily.

**Comment by Gerkiz** [comment]
Let me know if you have any other issues! Thanks for reporting 👍

**Comment by DeNarr** [comment]
So, it now gives points when I level, but I still seems to be out all the points from the levels I gained before. Also, I'm putting points into Magic, but not getting any Mana.

**Comment by Gerkiz** [comment]
I can't seem to reproduce. 
Could you post a how-to in order for me to reproduce this?

![alt text](https://imgshare.io/images/2020/09/24/g2H9OR.png)

**Comment by DeNarr** [comment]
Apply the mod to a game that was already started without the mod? Maybe there's some sort of conflict with other mods that also affect base stats?

**Comment by ElizTriad** [comment]
Can you make a recalculation button? If I already have 152 levels, just reset all achievements and give me as many points as I should have received by reaching this level.
