### ISSUE TITLE
Can't find documentation for controls

### ISSUE THREAD

**Issue by reallyhairydave** [Gerkiz/RPG#4]
So far the only one that I can't find is how to 'cast' spells, it's not clearly written anywhere I'm looking and I can't find options in the controls, mod settings or GUI settings menus or externally on the mod page.

**Comment by zombiekillerab** [comment]
I not sure if there is really any other way other than use a fish in the settings to spawn things, i had to add another mod called fish breeder i think the name is that but it ally me to spawn more fishes so i can keep using spells without having to be stuck with a limited amount

**Comment by ZeratulDM** [comment]
I have the same problem. I tried every key on my keyboard, but no spell was cast. I have enough mana and I selected a spell in the small panel. How should I cast my spells?

**Comment by zombiekillerab** [comment]
this is true however the fish supply isnt infinite meaning you do have a limited amount of spells without a fish farming methodthat also generate infinite amount even if it use resources of other types
