### ISSUE TITLE
Sometimes the mod does not work with saves that previously did not have the mod enabled.

### ISSUE THREAD

**Issue by Famous5000** [Gerkiz/RPG#5]
*save attached, this should give you everything you need to reproduce it.*

Attempt doing anything, get your first level, try to spend points in Magic and it doesn't work for some reason.
[bug.zip](https://github.com/Gerkiz/RPG/files/6017370/bug.zip)
Modlist is contained inside of the save. The 2 I added are this mod, and Editor Extensions. This should let you figure out what went wrong.

Note that it only happens on this save apparently, and I'm not sure what is causing the trouble. Any new saves work fine.

**Comment by Gerkiz** [comment]
Hi @Famous5000 - sorry for the 1 year delay respons :sadge:

This is fixed in 1.0.8.
