### ISSUE TITLE
Conflict with jetpack 0.2.12

### ISSUE THREAD

**Issue by ZeratulDM** [Gerkiz/RPG#6]
There is a conflict when using Earendel's jetpack 0.2.12 and RPG 1.06. On activating jetpack to fly, crafting speed and running speed are set to default value , deleting all bonuses from RPG mod. I am reporting this to Earendel's Discord channel too.

![image](https://user-images.githubusercontent.com/85700308/126810548-8d5b8587-eb25-4b9b-95ae-05911efaec97.png)

**Comment by Gerkiz** [comment]
Almost one year late answer, but Earendel is most likely overwriting these values. Sorry for the super late respons.
