### ISSUE TITLE
No Control

### ISSUE THREAD

**Issue by Argetlam-Elda** [Gerkiz/RPG#7]
When playing on a save in PVP mode (instead of freeplay), none of the buttons on the mod GUI do anything. I don't know if this is intended or not, but either way let me know.

**Comment by Gerkiz** [comment]
Could you please provide a step-by-step on how to reproduce this?

**Comment by Gerkiz** [comment]
@Argetlam-Elda this is hopefully fixed in 1.0.8. Try it out and report back if you can?

**Comment by Gerkiz** [comment]
Closing. Do reply back in this thread so we can open it again.
